version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: sbt test
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: sbt publish

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master